"""certificate signatures

Revision ID: f84116c0b429
Revises: a8831572b149
Create Date: 2026-09-28 21:18:56.648560+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f84116c0b429'
down_revision: Union[str, None] = 'a8831572b149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('certificates', sa.Column('signature', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_certificate_user_event_kind', 'certificates', ['user_id', 'event_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_certificate_user_event_kind', 'certificates', type_='unique')
    op.drop_column('certificates', 'signature')
    op.drop_column('certificates', 'payload')
    # ### end Alembic commands ###
