"""voting config audit event id

Revision ID: a8831572b149
Revises: 453bff1adc41
Create Date: 2026-09-28 11:05:46.962552+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'a8831572b149'
down_revision: Union[str, None] = '453bff1adc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('event_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=False)
    op.add_column('events', sa.Column('voting_mode', sa.String(length=20), server_default='auth', nullable=False))
    op.add_column('events', sa.Column('votes_per_voter', sa.Integer(), server_default='1', nullable=False))
    op.add_column('events', sa.Column('vote_credits', sa.Integer(), server_default='25', nullable=False))
    # votes.event_id: add nullable, backfill from the voted submission, then enforce NOT NULL
    op.add_column('votes', sa.Column('event_id', sa.String(length=36), nullable=True))
    op.execute('UPDATE votes SET event_id = (SELECT s.event_id FROM submissions s WHERE s.id = votes.submission_id)')
    op.alter_column('votes', 'event_id', nullable=False)
    op.execute("UPDATE audit_logs SET event_id = target_id WHERE target_type = 'event'")
    op.add_column('votes', sa.Column('ip_hash', sa.String(length=64), nullable=True))
    op.add_column('votes', sa.Column('weight', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_votes_event_id'), 'votes', ['event_id'], unique=False)
    op.create_index('ix_votes_event_voter', 'votes', ['event_id', 'voter_fingerprint'], unique=False)
    op.create_index(op.f('ix_votes_ip_hash'), 'votes', ['ip_hash'], unique=False)
    op.create_foreign_key('fk_votes_event_id', 'votes', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_votes_event_id', 'votes', type_='foreignkey')
    op.drop_index(op.f('ix_votes_ip_hash'), table_name='votes')
    op.drop_index('ix_votes_event_voter', table_name='votes')
    op.drop_index(op.f('ix_votes_event_id'), table_name='votes')
    op.drop_column('votes', 'weight')
    op.drop_column('votes', 'ip_hash')
    op.drop_column('votes', 'event_id')
    op.drop_column('events', 'vote_credits')
    op.drop_column('events', 'votes_per_voter')
    op.drop_column('events', 'voting_mode')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'event_id')
    # ### end Alembic commands ###
