"""audit log hash chain

Revision ID: 92b4257e6ce5
Revises: 632272ff424d
Create Date: 2026-09-29 12:03:45.809758+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '92b4257e6ce5'
down_revision: Union[str, None] = '632272ff424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GENESIS_HASH = "0" * 64


def upgrade() -> None:
    """Upgrade schema.

    Hand-adjusted from the autogenerated version: `prev_hash`/`hash` need a server_default so
    this doesn't fail against a database that already has audit_logs rows (a plain NOT NULL
    ADD COLUMN with no default is rejected by Postgres on a non-empty table). Rows from before
    this migration are backfilled with the genesis hash - they predate hash-chaining and are not
    individually verifiable, which `verify_chain` treats as the (documented) start of the chain
    rather than tampering. `seq` needs no such default: Postgres backfills a GENERATED BY DEFAULT
    AS IDENTITY column's existing rows from the sequence automatically.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.add_column('audit_logs', sa.Column('prev_hash', sa.String(length=64), nullable=False, server_default=GENESIS_HASH))
    op.add_column('audit_logs', sa.Column('hash', sa.String(length=64), nullable=False, server_default=GENESIS_HASH))
    op.alter_column('audit_logs', 'prev_hash', server_default=None)
    op.alter_column('audit_logs', 'hash', server_default=None)
    op.create_index(op.f('ix_audit_logs_seq'), 'audit_logs', ['seq'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_seq'), table_name='audit_logs')
    op.drop_column('audit_logs', 'hash')
    op.drop_column('audit_logs', 'prev_hash')
    op.drop_column('audit_logs', 'seq')
    # ### end Alembic commands ###
